# Generated by Django 5.0.14 on 2026-07-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('memory', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reviews_count', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=64, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=64, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
